# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ch.fhir.ig.ch-allergyintolerance
canonical: http://fhir.ch/ig/ch-allergyintolerance
name: CH-AllergyIntolerance
title: "CH-AllergyIntolerance (R4)"
description: Implementation guide CH-AllergyIntolerance (R4)
status: active
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2022-02-11
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: STU 1
publisher:
  name: HL7 Switzerland
contact:
  name: Walter Wellauer
  telecom:
    system: url
    value: https://www.hl7.ch
dependencies:
  ch.fhir.ig.ch-core: 2.0.0
  hl7.fhir.uv.ips:
    version: 1.0.0
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    id: ips

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#menu:
#  Home: index.html
#  Artifacts: artifacts.html
pages:
  index.md:
    title: Home
  document.md:
    title: Document
  usecase-english.md:
    title: Use cases
  usecase-french.md:
    title: Les cas d’utilisation 
  usecase-german.md:
    title: Anwendungsfälle   
  profiles.md:
    title: Profiles
  terminology.md:
    title: Terminology
  changelog.md:
    title: Change Log
  