# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ch.fhir.ig.ch-allergyintolerance
canonical: http://fhir.ch/ig/ch-allergyintolerance
name: CH-AllergyIntolerance
title: "CH AllergyIntolerance (R4)"
description: Implementation guide CH AllergyIntolerance (R4)
status: active
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2024-02-29
version: 3.0.0-ci-build
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: HL7 Switzerland
contact:
  name: eHealth Suisse
  telecom:
    system: url
    value: https://www.hl7.ch
dependencies:
  ch.fhir.ig.ch-core: current
  hl7.terminology: 5.4.0
  hl7.fhir.uv.ips:
    version: 1.0.0
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    id: ips

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#menu:
#  Home: index.html
#  Artifacts: artifacts.html
pages:
  index.md:
    title: Home
  document.md:
    title: Allergy Intolerance Document
  usecase-english.md:
    title: Clinical Use Case Scenarios
  usecase-french.md:
    title: Scénarios cliniques relatifs à des cas d’utilisation
  usecase-german.md:
    title: Klinische Anwendungsfall-Szenarien   
  profiles.md:
    title: Profiles
  terminology.md:
    title: Terminology
  changelog.md:
    title: Change Log

menu:
  Home: index.html
  Document: document.html
  Use Case:
    English: usecase-english.html
    French: usecase-french.html
    German: usecase-german.html
  Profiles: profiles.html
  Terminology: terminology.html
  Artifacts: artifacts.html

parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true
